### ISSUE TITLE
Feat: Search Page

### ISSUE THREAD

**Issue by LueKely** [LueKely/WYU-Frontend#34]

**Comment by LueKely** [comment]
naughty naughty raagas

**Comment by LueKely** [comment]
This is the first thing i shall do

**Comment by LueKely** [comment]
Finished ui @Jlscsr  ikaw na bahala sa connection dederecho na ko sa Profile page

**Comment by Jlscsr** [comment]
> Finished ui @Jlscsr ikaw na bahala sa connection dederecho na ko sa Profile page will close after this is all A-OK on the page

noted :>>
